### ISSUE TITLE
Trading Not Appearing & Nicknames Error

### ISSUE THREAD

**Issue by meanweenbean** [zjosua/Pokemanki#17]
For some reason, trading isn't available for me in the Pokemanki dropdown. Also, whenever I try to change the nickname of a pokemon, I get the following error: 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-09 19:57:01
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Anki2/addons21/1041307953/pokemon.py", line 22, in Nickname
    deckname = mw.col.decks.name(item[1])
  File "anki.decks", line 376, in name
  File "anki.decks", line 237, in get
ValueError: invalid literal for int() with base 10: 'marked'
```
Steps to reproduce the behavior:
1. Tools > Pokemanki > "Trading" option not visible
2. Tools > Pokemanki > Nicknames > Error occurs

```
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 12.6
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-10-09 19:57:01
```

**Comment by meanweenbean** [comment]
To fix this, I changed assign pokemon by tags to assign pokemon by decks then reset my cards.
