### ISSUE TITLE
Tool bar not working

### ISSUE THREAD

**Issue by mchait1** [zjosua/Pokemanki#22]
#### Describe the bug
*A clear and concise description of what the bug is.*
Hello,
I really like the add-on. But the tool bar has never worked for me, there is some bug. Even though it confirms that the changes are happening (I create the nickname, I give the ever stone, prestige, etc.), the changes never actually happen. When I click trade, nothing happens (the trade window doesn't open). There are no errors. 

One more thing is that in the stats screen, the Pokemon are kind of bunched up and it's hard to see the levels:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/116602680/197642582-d9f58b49-7637-4b3d-853b-a103b57065e8.png">

I'm using Anki Version ⁨2.1.54

*If Anki shows an error message, copy and paste it between the backticks below.*
```python

```

#### To Reproduce
1. .....
2. .....

#### Expected behavior
*A clear and concise description of what you expected to happen.*

#### What have you tried?
*Before we suggest or explore something you've already discovered to not work, tell us what you have already tried to fix the problem.*
- 

#### Screenshots
*If applicable, add screenshots to help explain your problem.*
Here are the addons I'm using:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/116602680/197642236-410654c3-9648-473a-915f-6d3b536d969e.png">

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```

```

What operating system are you using?
- OS: Mac OSX 12.6 Montery
- version:

#### Additional context
*Add any other context about the problem here.*

**Comment by Exkywor** [comment]
I'm gonna take a look at may be causing the Stats view to behave like that. It should be allocating enough space

**Comment by mchait1** [comment]
Thank you. I think the bigger problem is that none of the tool bar options are working though, even though they behave like they are. For example, I nickname a Pokemon and nothing changes. And the trade window does not come up, nothing happens when I click on trade.

**Comment by Exkywor** [comment]
Try the latest version and tell us if it has the same bug. I believe you should be able to trade properly now.

**Comment by mchait1** [comment]
The trade window now works (I haven't tried trading yet, I'll update you). But now, when I open the stats window to look at my Pokemon an error occurs:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.6.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-26 13:34:31
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/michaelchait/Library/Application Support/Anki2/addons21/1041307953/main.py", line 151, in <lambda>
    statsDialog.form.web.loadFinished.connect(lambda _: _onStatsOpen(statsDialog))
  File "/Users/michaelchait/Library/Application Support/Anki2/addons21/1041307953/main.py", line 145, in _onStatsOpen
    js = (addon_dir / "web.js").read_text()
  File "pathlib", line 1267, in read_text
  File "encodings.ascii", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)


The stats window comes up, but no Pokemon are there.

**Comment by cptmedic** [comment]
Same bug as above user on QT6 mac silicon edition

Editing main.py
from:
```python
js = (addon_dir / "web.js").read_text()
```
to
```python
js = (addon_dir / "web.js").read_text(encoding="UTF-8")
```

Gets rid of the error and appears to fix the issue of pokemon not displaying.

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/27046411/198346102-6135036e-0a6b-4900-9efb-9241b8f3f985.png">


@Exkywor or @zjosua if you guys want to confirm the above

**Comment by mchait1** [comment]
^ Yes this worked for me, thank you - The levels are still scrunched up but at least they're appearing again.

**Comment by Exkywor** [comment]
Try replacing the `view_stats.cs` file in your `pokemanki/pokemanki_css` folder with this: https://github.com/Exkywor/Pokemanki/blob/issue-22/src/pokemanki/pokemanki_css/view_stats.css

**Comment by Exkywor** [comment]
I'm also gonna have to rethink on displaying the deck they belong too, because even though now it should wrap the text properly, I'm not sure if having such long names looks good

**Comment by cptmedic** [comment]
> I'm also gonna have to rethink on displaying the deck they belong too, because even though now it should wrap the text properly, I'm not sure if having such long names looks good

I am down for trimming the deck name displayed to the lowest level (sub deck). My school uses a highly structured deck hierarchy so their are sub decks galore.

**Comment by cptmedic** [comment]
@Exkywor Question for you, I don't really know much about developing within anki, but can do some basic python and styling. Is there a way to enable like a developer console for the Anki stats menu. I feel like I remember seeing it somewhere but I cant seem to figure out how.

And as an edit:

The suggested CSS produced the following which corrects the overlapping
<img width="1636" alt="image" src="https://user-images.githubusercontent.com/27046411/198370016-602e51e3-a7a5-4a08-ae05-79b08e42eb7f.png">

**Comment by Exkywor** [comment]
Yeah, you can inspect the webview and weak it in the browser: https://addon-docs.ankiweb.net/debugging.html#webviews

**Comment by zjosua** [comment]
> I'm also gonna have to rethink on displaying the deck they belong too, because even though now it should wrap the text properly, I'm not sure if having such long names looks good

I was thinking about that too.
I suggest a configurable setting among the lines of "only display the lowest n decks".

**Comment by zjosua** [comment]
[AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032) also gives you dev tools in Anki.

**Comment by Exkywor** [comment]
> > I'm also gonna have to rethink on displaying the deck they belong too, because even though now it should wrap the text properly, I'm not sure if having such long names looks good
> 
> I was thinking about that too. I suggest a configurable setting among the lines of "only display the lowest n decks".

Hmm, that can work, I'm gonna take a look at that

**Comment by mchait1** [comment]
Just giving you an update: trading is working now for me, but the other functions of the tool bar are the same: the changes "go through" (prestige, ever stone, etc) but nothing happens

**Comment by cptmedic** [comment]
@mchait1 I looked a little bit into the everstone aspect. It appears to be writing the information to the file. However, my school schedule has been a bit hectic so thats about the extent I have gotten to. Not sure why its not recognizing that information in the stats page.

**Comment by zjosua** [comment]
@mchait have there been any changes regarding Pokémanki menu?
If it's still not working, please run `pp(mw.col.get_config("pokemanki"))` in Anki's debug console and paste the results here.
