### ISSUE TITLE
Appears QT5 variants of Anki no longer work

### ISSUE THREAD

**Issue by cptmedic** [zjosua/Pokemanki#24]
#### Describe the bug
On addon update and app restart getting new error about missing files for QT5. 

*If Anki shows an error message, copy and paste it between the backticks below.*
```python
Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 350, in onOpenProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "/Users/user/Library/Application Support/Anki2/addons21/pokemanki/__init__.py", line 40, in startup
    from . import main
  File "/Users/user/Library/Application Support/Anki2/addons21/pokemanki/main.py", line 28, in <module>
    from .gui.pokemanki_options import invoke_pokemanki_options
  File "/Users/user/Library/Application Support/Anki2/addons21/pokemanki/gui/pokemanki_options.py", line 52, in <module>
    from .forms import pokemanki_options
  File "/Users/user/Library/Application Support/Anki2/addons21/pokemanki/gui/forms/__init__.py", line 23, in <module>
    from .qt5 import *  # noqa: F401
ModuleNotFoundError: No module named 'pokemanki.gui.forms.qt5'

```

#### To Reproduce
1. QT5 variant of Anki
2. Install addon and relaunch

#### Expected behavior
Anki to launch normally with addon

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 13.0
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-26 19:47:29
Add-ons possibly involved: ⁨Pokémanki⁩
```

**Comment by zjosua** [comment]
That is correct. And I don't plan to add Qt5 support.

**Comment by cptmedic** [comment]
Awesome, thank you for the reply. I made it as a bug issue because it looked like the auto generated code seemed to think there would be QT5 support. Mainly have stuck on QT5 variant because I use several of the addons from the AnkiPalace Butler that are supposedly broken on QT6 (albeit I haven't checked recently).
