### ISSUE TITLE
Everstonepokemonlist IndexError

### ISSUE THREAD

**Issue by ahodapp11** [zjosua/Pokemanki#28]
#### Troubleshooting Checklist
*Replace the space between the parentheses with an x to mark the items as verified.*
- [x] I have veryfied that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*
- [X] I am using the latest version of the add-on from AnkiWeb. **With modifications suggested in #27.**
- [X] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).

#### Describe the bug
Continuation of pokemon not showing up in stats page: I have edited line 145 and now am met with a new error message when I click on collection in the stats page. 

*If Anki shows an error message, copy and paste it between the backticks below.*
```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.5.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-02 07:46:46
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 431, in MultiPokemon
    name = everstonepokemonlist[idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/main.py", line 132, in message_handler
    html = pokemon_display(f, True).replace("`", "'")
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/display.py", line 61, in pokemon_display
    pokemon = MultiPokemon(wholecollection)
  File "/Users/andreahodapp/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 438, in MultiPokemon
    everstonepokemonlist.pop(idx)
IndexError: pop index out of range

```

#### To Reproduce
1. Open Anki
2. Open Stats
3. Open Collection

#### What have you tried?
As suggested from #27 I edited line 145 in main.py to js = (addon_dir / "web.js").read_text(encoding="utf-8")

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 12.5.1
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-11-02 07:46:46
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2022-09-08T08:45, 'None', mod]
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
    Pokmanki ['1041307953', 2022-10-26T15:22, 'None', '']
    Special Fields ['1102281552', 2022-02-23T12:27, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1041307953 1102281552 594329229
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Pokémanki ['pokemanki', 2022-10-26T14:58, 'None', '']

```

What operating system are you using?
Mac

#### Additional context
Thank you for all of your help!

**Comment by zjosua** [comment]
Thanks for the report. This seems to be unrelated to #27. I changed the title accordingly.
Will look into it later.
