### ISSUE TITLE
Bug Report - Help a Med Student out plz

### ISSUE THREAD

**Issue by Aurichamp** [zjosua/Pokemanki#30]
#### Troubleshooting Checklist
*Replace the space between the parentheses with an x to mark the items as verified.*
- [x ] I have veryfied that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*
- [x ] I am using the latest version of the add-on from AnkiWeb.
- [ x] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).

#### Describe the bug
*When I launch anki, the add on doesn't work or appear in the bar.*

*If Anki shows an error message, copy and paste it between the backticks below.*
```Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-04 17:03:50

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 290, in setupProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "C:\Users\Aurichamp\AppData\Roaming\Anki2\addons21\1041307953\__init__.py", line 40, in startup
    from . import main
  File "C:\Users\Aurichamp\AppData\Roaming\Anki2\addons21\1041307953\main.py", line 28, in <module>
    from .gui.pokemanki_options import invoke_pokemanki_options
  File "C:\Users\Aurichamp\AppData\Roaming\Anki2\addons21\1041307953\gui\pokemanki_options.py", line 52, in <module>
    from .forms import pokemanki_options
  File "C:\Users\Aurichamp\AppData\Roaming\Anki2\addons21\1041307953\gui\forms\__init__.py", line 23, in <module>
    from .qt5 import *  # noqa: F401
ModuleNotFoundError: No module named '1041307953.gui.forms.qt5'
```

#### To Reproduce
1. Download add on
2. Restart Anki

#### Expected behavior
*For it to work.*

#### What have you tried?
*Deleting and reinstalling the add-on.*

#### Screenshots
*If applicable, add screenshots to help explain your problem.*

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```

```

**Comment by Aurichamp** [comment]
It's probably that I have the qt5 build? Is there a version of pokimanki that works with that version? (I think many of my other add ons wont work to qt6, I'm speaking ignorantly though, I know a lot more about human anatomy than my own anki software).

Thank you!

**Comment by zjosua** [comment]
Yes, as you can read from the error message, you are using Anki's Qt5 build.
[Version 1.0.0](https://github.com/zjosua/Pokemanki/releases/tag/v1.0.0) *might* work with Qt5, but I really can't be bothered to check properly.

**Comment by zjosua** [comment]
Closing due to inactivity.
