### ISSUE TITLE
Error when accessing Stats

### ISSUE THREAD

**Issue by s0nik42** [zjosua/Pokemanki#35]
#### Troubleshooting Checklist
*Replace the space between the parentheses with an x to mark the items as verified.*
- [x] I have veryfied that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*
- [x] I am using the latest version of the add-on from AnkiWeb.
- [x] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).

#### Describe the bug
Cannot load the stats menu without getting an error.
I have 3 profiles.
2 works, one is failing with the error below.

*If Anki shows an error message, copy and paste it between the backticks below.*
```python
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-08 17:59:06
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/Volumes/Data Disk/Users/s0nik42/Library/Application Support/Anki2/addons21/1041307953/main.py", line 138, in message_handler
    html = pokemon_display(f, True).replace("`", "'")
  File "/Volumes/Data Disk/Users/s0nik42/Library/Application Support/Anki2/addons21/1041307953/display.py", line 48, in pokemon_display
    pokemon = MultiPokemon(wholecollection)
  File "/Volumes/Data Disk/Users/s0nik42/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 466, in MultiPokemon
    if name.startswith("Eevee"):
AttributeError: 'int' object has no attribute 'startswith'

```

#### To Reproduce
1. Start Anki
2. Seect the Profile
3. Click on stats
4. Click on collection

#### Expected behavior
*A clear and concise description of what you expected to happen.*

#### What have you tried?
I remove the collection.media/_*.json to wipe the previous configuration, same error again.

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 13.1
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-01-08 17:59:06
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Pokmanki ['1041307953', 2022-12-05T08:29, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1041307953
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

What operating system are you using?
- OS: MacOs
- version: ventura

**Comment by thepeacemonk** [comment]
Same error here!

**Comment by underaverage23** [comment]
Same error here
