### ISSUE TITLE
Error when starting new Pokemanki deck

### ISSUE THREAD

**Issue by moniquemurphy** [zjosua/Pokemanki#44]
#### Troubleshooting Checklist
*Replace the space between the parentheses with an x to mark the items as verified.*
- [x] I have verified that my issue has not been reported yet in the [issue tracker](https://github.com/zjosua/Pokemanki/issues?q=is%3Aissue).
      *If you have an issue that has already been reported, join the discussion of the existing issue instead of creating a new one.*
- [x] I am using the latest version of the add-on from AnkiWeb.
- [x] My Anki installation meets the [compatibility requirements](https://github.com/zjosua/Pokemanki#compatibility).

#### Describe the bug
I did a fresh install of the addon this morning, 9/18/2023. I have never used Pokemanki before. When I go to the Stats tab, I am prompted to choose a deck for my starter Pokemon, but then the addon crashes. 

*If Anki shows an error message, copy and paste it between the backticks below.*
```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-12.6.3-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-18 08:35:16
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 656, in _onBridgeCmd
  File "_aqt.hooks", line 5255, in __call__
  File "/Users/monique/Library/Application Support/Anki2/addons21/1041307953/main.py", line 136, in message_handler
    html = pokemon_display(f, False).replace("`", "'")
  File "/Users/monique/Library/Application Support/Anki2/addons21/1041307953/display.py", line 48, in pokemon_display
    pokemon = MultiPokemon(wholecollection)
  File "/Users/monique/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 316, in MultiPokemon
    FirstPokemon()
  File "/Users/monique/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 244, in FirstPokemon
    deckmon = msgbox.clickedButton().text()
AttributeError: 'NoneType' object has no attribute 'text'

```

#### To Reproduce
1. Open Anki (with no Pokemanki deck ever having been created)
2. Go to Stats
3. Choose a deck when prompted for starter deck. Click "OK."

#### Expected behavior
I expected a popup for started Pokemon to display after the starter deck prompt. 

#### What have you tried?
I made a comment in [a previous issue](https://github.com/zjosua/Pokemanki/issues/43) but that issue didn't end up being related to this bug, so I thought maybe it would be fixed with the update. It seems like there's an issue with the starter Pokemon `QTMessageBox()` being out of scope? 

#### Screenshots
*If applicable, add screenshots to help explain your problem.*

#### Information about your set-up
*Open Anki, go to Help > About and click on "Copy Debug Info". Paste the result between the backticks below.*
```
    
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
    Platform: macOS-12.6.3-x86_64-i386-64bit
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-09-18 08:35:16
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['memrise2anki-extension-4d0a5d7f1ffd66d8f90c70f7738113b10ef3ba25', 0, 'None', '']
    Change Order of Review Cards in Regular Decks ['3731265543', 2018-10-12T15:47, 'None', '']
    FSRS4Anki Helper ['759844606', 2023-09-14T21:15, 'None', mod]
    Japanese Support ['3918629684', 2022-03-13T20:32, 'None', '']
    Pokmanki ['1041307953', 2023-09-17T05:40, 'None', '']
    Straight Reward ['957961234', 2022-12-12T05:49, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1041307953 3731265543 3918629684 759844606 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Auto Ease Factor ['1672712021', 2021-03-21T11:11, 'None', mod]
    Review Heatmap ['review_heatmap', 2018-10-28T15:06, 'None', '']
    autoLapseNewInterval  automatically adjust the new interval after a lapse ['372281481', 2022-09-28T00:26, 'None', '']

```

What operating system are you using?
- OS: Mac OS X
- version: Monterrey

#### Additional context
*Add any other context about the problem here.*

**Comment by dochypermoose** [comment]
Having the same bug ... despite the update released today

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-12.6.3-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-20 20:30:19
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 656, in _onBridgeCmd
  File "_aqt.hooks", line 5255, in __call__
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/1041307953/main.py", line 136, in message_handler
    html = pokemon_display(f, False).replace("`", "'")
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/1041307953/display.py", line 48, in pokemon_display
    pokemon = MultiPokemon(wholecollection)
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 317, in MultiPokemon
    FirstPokemon()
  File "/Users/dochypermoose/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 244, in FirstPokemon
    deckmon = msgbox.clickedButton().text()
AttributeError: 'NoneType' object has no attribute 'text'


    
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
    Platform: macOS-12.6.3-x86_64-i386-64bit
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2023-09-20 20:30:19
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Pokmanki ['1041307953', 2023-09-20T16:18, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1041307953
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
**This is my test account, no active add-ons except the one I'm troubleshooting

**Comment by paellinee** [comment]
I have no other add-ons, and I have exactly the same problem. Please, can you debug it, i reeeeeally need a pokemon team :(
